services:
  postgres:
    image: postgres:17-alpine
    container_name: smartcart-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - smartcart-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: smartcart-ollama
    restart: unless-stopped

    ports:
      - "11434:11434"

    volumes:
      - ollama-data:/root/.ollama

    networks:
      - smartcart-network

    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile

    container_name: smartcart-backend
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: tinyllama

    ports:
      - "8000:8000"

    networks:
      - smartcart-network

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile

    container_name: smartcart-frontend
    restart: unless-stopped

    ports:
      - "8080:80"

    networks:
      - smartcart-network


volumes:
  postgres-data:
  ollama-data:


networks:
  smartcart-network:
    driver: bridge