server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Forward frontend API requests to the FastAPI backend.
    #
    # Browser requests:
    #   /api/products
    #
    # Nginx forwards them internally as:
    #   http://backend:8000/products
    #
    # The /api prefix is removed before reaching FastAPI.
    location /api/ {
        proxy_pass http://backend:8000/;

        proxy_http_version 1.1;

        # AI requests can take longer because Ollama
        # generates responses locally on CPU
        proxy_connect_timeout 10s;
        proxy_send_timeout 180s;
        proxy_read_timeout 180s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serve the React application.
    #
    # Keeping this fallback is important for React Router.
    # For example, /orders or /admin should still return
    # index.html instead of a 404 from Nginx.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
