# Common sensitive configuration for SmartCart.
#
# These are development credentials for the local portfolio project.
#
# Values under "data" must be Base64 encoded.
# Base64 is encoding, NOT encryption.

apiVersion: v1
kind: Secret

metadata:
  name: smartcart-secrets
  namespace: smartcart

type: Opaque

data:
  POSTGRES_USER: c21hcnRjYXJ0
  POSTGRES_PASSWORD: c21hcnRjYXJ0X2Rldl9wYXNzd29yZA==
  JWT_SECRET_KEY: MjU2ODM1ZWY4ZTFiYmRmNzM3NjIyZTNhOWI0YjM5MGQxNTUxMmVmOGViMTNiZGZjOTgzNDRjNTc4YmM4Yzc3Yw==