# Synchronizes SmartCart secrets from Vault
# into a Kubernetes Secret.
#
# Vault:
#   secret/smartcart
#
# Kubernetes:
#   smartcart-secrets

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret

metadata:
  name: smartcart-secrets

spec:
  # Vault KV engine type.
  type: kv-v2

  # KV engine mount.
  mount: secret

  # Secret path inside Vault.
  path: smartcart

  # Kubernetes Secret created and maintained by VSO.
  destination:
    name: smartcart-secrets
    create: true

  # Use the VaultAuth resource above.
  vaultAuthRef: smartcart