# Default values for the SmartCart Helm chart.

backend:
  image:
    repository: pankajbehera/smartcart-backend
    tag: "e3df12c17829732b78a85554f6b150b5881ae4fc"
  replicas: 1
frontend:
  image:
    repository: pankajbehera/smartcart-frontend
    tag: "e3df12c17829732b78a85554f6b150b5881ae4fc"
  replicas: 1
ollama:
  image:
    repository: ollama/ollama
    tag: latest
  replicas: 1
postgres:
  image:
    repository: postgres
    tag: "17-alpine"
  storage: 2Gi
hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuTarget: 70
ollamaStorage: 5Gi
ingress:
  enabled: true
  className: nginx
  host: smartcart-helm.local
  proxyReadTimeout: "180"
  proxySendTimeout: "180"
# Vault authentication configuration
vault:
  role: smartcart-helm
