apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: smartcart-secrets
  namespace: smartcart
spec:
  type: kv-v2

  # Use the VaultConnection created above.
  mount: secret
  path: smartcart

  # Create/update this Kubernetes Secret.
  destination:
    name: smartcart-secrets
    create: true

  # Authenticate to Vault using our SmartCart service account.
  vaultAuthRef: smartcart
