apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: smartcart
  namespace: smartcart
spec:
  vaultConnectionRef: vault

  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: smartcart
    serviceAccount: smartcart-vault
